export const INDIAN_STOCKS = [
  { symbol: "RELIANCE.NS", name: "Reliance Industries" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank" },
  { symbol: "INFY.NS", name: "Infosys" },
  { symbol: "ITC.NS", name: "ITC Limited" },
  { symbol: "SBIN.NS", name: "State Bank of India" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel" },
  { symbol: "L&T.NS", name: "Larsen & Toubro" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever" },
  { symbol: "AXISBANK.NS", name: "Axis Bank" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical" },
  { symbol: "NTPC.NS", name: "NTPC Limited" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement" },
  { symbol: "TITAN.NS", name: "Titan Company" },
  { symbol: "ONGC.NS", name: "Oil and Natural Gas Corp" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corp" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra" },
  { symbol: "WIPRO.NS", name: "Wipro" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports" },
  { symbol: "COALINDIA.NS", name: "Coal India" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel" },
  { symbol: "GRASIM.NS", name: "Grasim Industries" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries" },
  { symbol: "TECHM.NS", name: "Tech Mahindra" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance" },
  { symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories" },
  { symbol: "CIPLA.NS", name: "Cipla" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp" },
  { symbol: "LTIM.NS", name: "LTIMindtree" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto" },
  { symbol: "UPL.NS", name: "UPL Limited" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum" },
  { symbol: "NESTLEIND.NS", name: "Nestle India" },
  
  // Adding popular global stocks as well
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corp." },
  { symbol: "GOOGL", name: "Alphabet Inc." },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "NVDA", name: "NVIDIA Corp." },
  { symbol: "TSLA", name: "Tesla Inc." },
  { symbol: "META", name: "Meta Platforms Inc." }
];
