import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1e293b',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    color: '#0f172a',
    fontWeight: 'bold',
  },
  subtitle: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 4,
  },
  section: {
    margin: 10,
    padding: 10,
  },
  sectionTitle: {
    fontSize: 14,
    color: '#0f172a',
    fontWeight: 'bold',
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 4,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  label: {
    width: 120,
    fontSize: 10,
    color: '#64748b',
  },
  value: {
    fontSize: 10,
    color: '#0f172a',
    flex: 1,
  },
  recommendationBox: {
    backgroundColor: '#f8fafc',
    padding: 10,
    borderRadius: 4,
    marginBottom: 15,
  },
  recommendationText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  thesisText: {
    fontSize: 10,
    lineHeight: 1.5,
    color: '#334155',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: 8,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 10,
  }
});

interface InstitutionalReportPDFProps {
  reportData: any;
  symbol: string;
  recommendation: string;
  confidence: number;
  date: string;
}

export function InstitutionalReportPDF({ reportData, symbol, recommendation, confidence, date }: InstitutionalReportPDFProps) {
  
  // Safely parse JSON if it's a string
  let parsed = reportData;
  if (typeof reportData === 'string') {
    try {
      parsed = JSON.parse(reportData);
    } catch (e) {
      parsed = {};
    }
  }

  const recColor = recommendation === 'BUY' ? '#16a34a' : recommendation === 'SELL' ? '#dc2626' : '#ca8a04';

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        
        {/* Header Section */}
        <View style={styles.header}>
          <Text style={styles.title}>Quantan AI Institutional Report</Text>
          <Text style={styles.subtitle}>Automated Equity Research for {symbol} | Generated: {date}</Text>
        </View>

        {/* Recommendation Section */}
        <View style={styles.recommendationBox}>
          <Text style={[styles.recommendationText, { color: recColor }]}>
            AI Recommendation: {recommendation} (Confidence: {(confidence * 100).toFixed(1)}%)
          </Text>
          <Text style={{ fontSize: 10, marginTop: 6, color: '#475569' }}>
            {parsed.investment_thesis || "Investment thesis was generated by Quantan Alpha Engine based on multi-factor analysis."}
          </Text>
        </View>

        {/* Technical & Fundamental Analysis */}
        <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
          <View style={{ width: '48%' }}>
            <Text style={styles.sectionTitle}>Technical Analysis</Text>
            <View style={styles.row}>
              <Text style={styles.label}>Technical Score:</Text>
              <Text style={styles.value}>{parsed.technical_score?.toFixed(1) || 'N/A'}/100</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>Trend:</Text>
              <Text style={styles.value}>{parsed.technical_trend || 'N/A'}</Text>
            </View>
          </View>

          <View style={{ width: '48%' }}>
            <Text style={styles.sectionTitle}>Fundamental Analysis</Text>
            <View style={styles.row}>
              <Text style={styles.label}>Fundamental Score:</Text>
              <Text style={styles.value}>{parsed.fundamental_score?.toFixed(1) || 'N/A'}/100</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>Value Assessment:</Text>
              <Text style={styles.value}>{parsed.fundamental_valuation || 'N/A'}</Text>
            </View>
          </View>
        </View>

        {/* Sentiment & Risk Analysis */}
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 15 }}>
          <View style={{ width: '48%' }}>
            <Text style={styles.sectionTitle}>Sentiment Analysis</Text>
            <View style={styles.row}>
              <Text style={styles.label}>FinBERT Score:</Text>
              <Text style={styles.value}>{parsed.sentiment_score?.toFixed(1) || 'N/A'}/100</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>News Volume:</Text>
              <Text style={styles.value}>{parsed.news_volume || 'High'}</Text>
            </View>
          </View>

          <View style={{ width: '48%' }}>
            <Text style={styles.sectionTitle}>Risk Profile</Text>
            <View style={styles.row}>
              <Text style={styles.label}>Risk Score:</Text>
              <Text style={styles.value}>{parsed.risk_score?.toFixed(1) || 'N/A'}/100</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>Volatility Level:</Text>
              <Text style={styles.value}>{parsed.volatility_level || 'Moderate'}</Text>
            </View>
          </View>
        </View>

        {/* Strengths & Weaknesses (SHAP / Explanations) */}
        <View style={{ marginTop: 20 }}>
          <Text style={styles.sectionTitle}>Key Drivers (SHAP Explainability)</Text>
          <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
            <View style={{ width: '48%' }}>
              <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#16a34a', marginBottom: 4 }}>Bullish Factors</Text>
              {(parsed.strengths || []).slice(0, 4).map((str: string, i: number) => (
                <Text key={i} style={{ fontSize: 9, color: '#334155', marginBottom: 2 }}>• {str}</Text>
              ))}
            </View>
            <View style={{ width: '48%' }}>
              <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#dc2626', marginBottom: 4 }}>Bearish Factors</Text>
              {(parsed.weaknesses || parsed.risk_factors || []).slice(0, 4).map((str: string, i: number) => (
                <Text key={i} style={{ fontSize: 9, color: '#334155', marginBottom: 2 }}>• {str}</Text>
              ))}
            </View>
          </View>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          This report is generated automatically by Quantan AI. Past performance is not indicative of future results. For institutional use only.
        </Text>
      </Page>
    </Document>
  );
}
